//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProjectCreatorUI.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewProjectCreatorUI.Resources.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Creator UI.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code from an online repository like GitHub, GitLab, or Azure DevOps.
        /// </summary>
        public static string Launcher_CloneRepository_Description {
            get {
                return ResourceManager.GetString("Launcher.CloneRepository.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone a Repository.
        /// </summary>
        public static string Launcher_CloneRepository_Label {
            get {
                return ResourceManager.GetString("Launcher.CloneRepository.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a project template with code scaffolding to get started..
        /// </summary>
        public static string Launcher_CreateNewProject_Description {
            get {
                return ResourceManager.GetString("Launcher.CreateNewProject.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Project.
        /// </summary>
        public static string Launcher_CreateNewProject_Label {
            get {
                return ResourceManager.GetString("Launcher.CreateNewProject.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Launcher_GetStarted_Label {
            get {
                return ResourceManager.GetString("Launcher.GetStarted.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Launcher_OpenFolder_Label {
            get {
                return ResourceManager.GetString("Launcher.OpenFolder.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a folder (and any code contained within) in an IDE or Code Editor..
        /// </summary>
        public static string Launcher_OpenLocalFolder_Description {
            get {
                return ResourceManager.GetString("Launcher.OpenLocalFolder.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Local Folder.
        /// </summary>
        public static string Launcher_OpenLocalFolder_Label {
            get {
                return ResourceManager.GetString("Launcher.OpenLocalFolder.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Visual Studio project, a CSPROJ based project, or a .sln file.
        /// </summary>
        public static string Launcher_OpenProjectOrSolution_Description {
            get {
                return ResourceManager.GetString("Launcher.OpenProjectOrSolution.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Project or Solution.
        /// </summary>
        public static string Launcher_OpenProjectOrSolution_Label {
            get {
                return ResourceManager.GetString("Launcher.OpenProjectOrSolution.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string Launcher_OpenRecent_Label {
            get {
                return ResourceManager.GetString("Launcher.OpenRecent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Recent.
        /// </summary>
        public static string Launcher_SearchRecent_Label {
            get {
                return ResourceManager.GetString("Launcher.SearchRecent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse a Repository.
        /// </summary>
        public static string RepoCloner_Browse_Label {
            get {
                return ResourceManager.GetString("RepoCloner.Browse.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone folder.
        /// </summary>
        public static string RepoCloner_CloneFolder_Label {
            get {
                return ResourceManager.GetString("RepoCloner.CloneFolder.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository URL.
        /// </summary>
        public static string RepoCloner_RepoUrl_Label {
            get {
                return ResourceManager.GetString("RepoCloner.RepoUrl.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Git Repository URL.
        /// </summary>
        public static string RepoCloner_RepoUrlEntry_Label {
            get {
                return ResourceManager.GetString("RepoCloner.RepoUrlEntry.Label", resourceCulture);
            }
        }
    }
}
